version: '3.8'

services:
  mongodb:
    image: mongo:5
    container_name: video-qa-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - video-qa-network
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: video-qa-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - video-qa-network
    restart: unless-stopped

  chromadb:
    image: chromadb/chroma:latest
    container_name: video-qa-chromadb
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma_data
      - ALLOW_RESET=TRUE
    volumes:
      - chromadb_data:/chroma_data
    networks:
      - video-qa-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/api/v2/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  mongodb_data:
  redis_data:
  chromadb_data:

networks:
  video-qa-network:
    driver: bridge